1

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,20 +1,12 @@
 options:
   logging: CLOUD_LOGGING_ONLY
 
-
-
 steps:
   - name: "ubuntu"
     entrypoint: "bash"
     args:
       - "-c"
       - |
-        echo "This is a test build for product-a main branch"
-
-
-
-
-
-
-
+        echo "This will fail"
+        exit 1
 
